### ISSUE TITLE
QT Issues

### ISSUE THREAD

**Issue by skade** [ferrous-systems/qt-training-2023#1]
This is an issue collecting tasks that are QT specific.

```[tasklist]
### QT specific training bits
- [ ] QT/cxx-qt installation instructions https://github.com/ferrous-systems/qt-training-2023/blob/main/book/src/setup.md#additional-tooling
- [ ] Provide tooling check for QT/cxx-qt tooling https://github.com/ferrous-systems/qt-training-2023/blob/main/book/src/tooling-check.md#qt-specifics
- [ ] Add QT app using the image-manipulation library
```

**Comment by LeonMatthesKDAB** [comment]
You can find a fork of this training material [here](https://github.com/leonmattheskdab/qt-training-2023).
I'll add the Qt specific section there and open a PR.

**Comment by skade** [comment]
@LeonMatthesKDAB last commit adds a "with-workspace" solution that has a CLI app and an `image-manipulation` crate. You could use this to write a very small QT example around.

**Comment by LeonMatthesKDAB** [comment]
Okay, I'm currently using `rustagram` in the example in #2 directly.
But can update this to use the library from the workspace on Friday.

**Comment by skade** [comment]
I may take a stab at it tomorrow if it’s okay, gives a natural check for the QT parts.

—

Florian Gilcher (He/Him)
Managing Director

m. +49 172 8122469

Ferrous Systems GmbH
Boxhagener Straße 79
D-10245 Berlin

AG Charlottenburg, HRB 200196
Geschäftsführung: Felix Gilcher, Florian Gilcher
________________________________

**Comment by LeonMatthesKDAB** [comment]
As the training has been held already, I guess we can close this.
